# Generated by Django 4.0.3 on 2022-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_remove_saveanalysis_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveanalysis',
            name='summary',
            field=models.CharField(default='Please write some summary for future reference', max_length=500),
        ),
    ]
