# Generated by Django 4.0.3 on 2022-05-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0004_alter_saveanalysis_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveanalysis',
            name='summary',
            field=models.TextField(),
        ),
    ]
