# Generated by Django 4.0.3 on 2022-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0002_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
